### ISSUE TITLE
Socket error on client, disconnecting

### ISSUE THREAD

**Issue by itSQualL** [gausby/tortoise#101]
Im trying to connect to mosquitto broker with MQTT v3.1

On mosquitto logs it appears as:

```
1549733781: New client connected from 127.0.0.1 as sunflowex (c1, k60).
1549733781: Socket error on client sunflowex, disconnecting.
```

And on console the log says:

```
18:39:26.106 [info]  Application sunflowex exited: an exception was raised:                                                                                                                                        
    ** (CaseClauseError) no case clause matching: {:error, :badarg}                                                                                                                                                
        (tortoise) lib/tortoise/connection/receiver.ex:37: Tortoise.Connection.Receiver.handle_socket/2                                                                                                            
        (tortoise) lib/tortoise/connection.ex:623: Tortoise.Connection.init_connection/2                                                                                                                           
        (tortoise) lib/tortoise/connection.ex:386: Tortoise.Connection.handle_info/2                                                                                                                               
        (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4                                                                                                                                                    
        (stdlib) gen_server.erl:686: :gen_server.handle_msg/6                                                                                                                                                      
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

The code: 

```
Tortoise.Supervisor.start_child(
      client_id: "sunflowex",
      handler: {Sunflowex.MqttClient, []},
      server: {Tortoise.Transport.Tcp, host: "127.0.0.1", port: 1883},
      subscriptions: [{"engine/#", 1}])
```

I don't know what can be happening because it was working a week ago :thinking:

**Comment by itSQualL** [comment]
Fixed. 

It was a problem with TCP connections on OTP 20.3. It works fine on OTP >= v20.3.8

**Comment by gausby** [comment]
Great!

Sorry I am a bit slow at responding at the moment. I have moved into a new apartment, and I don't have the internet yet. I am working on a huge upgrade to Tortoise though, so MQTT 5 support should arrive sometime in the future.

Cool that you are using the library. Let me hear what you are using it for if you have time some day :)
