### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by brianmay** [gausby/tortoise#111]
Hello,

Wondering if it is possible to use this library with IPv6? Normal method with Elixir is to pass `:inet6` somehow through socket options, but I don't see any way of doing that here.

I have tried setting:

```
server: {
...
opts: [:inet6],
}
```

However, so appears to give `:gen_tcp.connect` an invalid opts value of:

```
[:binary, {:packet, :raw}, {:active, false}, {:opts, [:inet6]}]
```

Where it should be (if I understand correctly):

```
[:binary, {:packet, :raw}, {:active, false}, :inet6]
```

OK, so what I did is obviously not correct, however my attempts so far to try to get a plain `:inet6` value passed have been failures...

Will keep trying...

Thanks.

**Comment by brianmay** [comment]
I think the most hopeful is this:

```
       server: {                                                                 
         Tortoise.Transport.Tcp,                                                 
         [{:host, mqtt_host}, {:port, 1883}, :inet6]                             
       },
```

But this results in an error when we try to pass this list to `Keyword.pop()`, presumably because it isn't actually a Keyword list:

```
        ** (FunctionClauseError) no function clause matching in Keyword.delete_key/2
            (elixir) lib/keyword.ex:515: Keyword.delete_key([:inet6], :host)
            (elixir) lib/keyword.ex:520: Keyword.delete_key/2
            (elixir) lib/keyword.ex:510: Keyword.pop/3
            (tortoise) lib/tortoise/transport/tcp.ex:10: Tortoise.Transport.Tcp.new/1
            (tortoise) lib/tortoise/transport.ex:29: Tortoise.Transport.new/1
            (tortoise) lib/tortoise/connection.ex:38: Tortoise.Connection.start_link/2
            (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
            (stdlib) supervisor.erl:1157: :supervisor.children_map/4
            (stdlib) supervisor.erl:315: :supervisor.init_children/2
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by brianmay** [comment]
I would suggest something like the following (can turn this into a PR if you agree):

```
diff --git a/lib/tortoise/transport/ssl.ex b/lib/tortoise/transport/ssl.ex
index 1dc7bb6..e6a7091 100644
--- a/lib/tortoise/transport/ssl.ex
+++ b/lib/tortoise/transport/ssl.ex
@@ -11,9 +11,10 @@ defmodule Tortoise.Transport.SSL do
   def new(opts) do
     {host, opts} = Keyword.pop(opts, :host)
     {port, opts} = Keyword.pop(opts, :port)
+    {list_opts, opts} = Keyword.pop(opts, :opts, [])
     host = coerce_host(host)
     opts = Keyword.merge(@default_opts, opts)
-    opts = [:binary, {:packet, :raw}, {:active, false} | opts]
+    opts = [:binary, {:packet, :raw}, {:active, false} | opts] ++ list_opts
     %Transport{type: __MODULE__, host: host, port: port, opts: opts}
   end
 
diff --git a/lib/tortoise/transport/tcp.ex b/lib/tortoise/transport/tcp.ex
index 7604903..2d28ddc 100644
--- a/lib/tortoise/transport/tcp.ex
+++ b/lib/tortoise/transport/tcp.ex
@@ -9,8 +9,9 @@ defmodule Tortoise.Transport.Tcp do
   def new(opts) do
     {host, opts} = Keyword.pop(opts, :host)
     {port, opts} = Keyword.pop(opts, :port, 1883)
+    {list_opts, opts} = Keyword.pop(opts, :opts, [])
     host = coerce_host(host)
-    opts = [:binary, {:packet, :raw}, {:active, false} | opts]
+    opts = [:binary, {:packet, :raw}, {:active, false} | opts] ++ list_opts
     %Transport{type: __MODULE__, host: host, port: port, opts: opts}
   end
```

**Comment by brianmay** [comment]
With that change, the config I tried in my first message will work.

**Comment by adriankumpf** [comment]
I am having the same problem. Passing `:inet6` results in an error because `opts` is no longer a keyword list.

It would be fantastic if @brianmay's proposal would be implemented. I can also create a PR if that's okay with you, @gausby?

**Comment by brianmay** [comment]
I forgot making this issue...

I recommend making the PR.

**Comment by tohojo** [comment]
Turned @brianmay 's proposed patch into a PR in #126
