### ISSUE TITLE
Unclear failure mode, failing to connect to AWS IoT using Tortoise.Transport.SSL config

### ISSUE THREAD

**Issue by powersjcb** [gausby/tortoise#62]
Hi there, I'm new to elixir and I'm running into an issue using Tortoise with the SSL configs against an AWS IoT broker.

My workflow so far has been:
1. Setup a mosquitto broker ✅ 
2. Send messages to the broker using Tortoise ✅ 
3. Configure the broker in bridge mode, add valid authenticated certificates, and proxy the requests to AWS IoT. (Mosquitto running in docker, elixir running native on mac, events are successfully ingested into AWS.) ✅ 
4. Attempt to configure Tortoise to use the same certificates to connect to the same AWS IoT endpoint. ❌ 

Any hints at what this problem looks like? (I'm worried it might be a firewall issue.)

```
    Tortoise.Supervisor.start_child(
      client_id: config.client_id,
      version: config.version,
      handler: {Tortoise.Handler.Logger, []},
      server: {
        Tortoise.Transport.SSL,
        host: config.host,
        port: config.port,
        certfile: './config/client-certificate.pem.key',  # tried using either `cert` or `certfile`
        keyfile: './config/client-private.pem.key',
        cacertfile: config.cacertfile,
        protocol_version: :"tlsv1.2"
      },
      subscriptions: [{"#", 0}]
    )
```

Here's the relevant part of the current stack trace when it fails:
```State: %Tortoise.Connection{backoff: %Tortoise.Connection.Backoff{max_interval: 30000, min_interval: 100, value: nil}, connect: %Tortoise.Package.Connect{__META__: %Tortoise.Package.Meta{flags: 0, opcode: 1}, clean_session: true, client_id: nil, keep_alive: 60, password: nil, protocol: "MQTT", protocol_version: 4, user_name: nil, will: nil}, keep_alive: nil, opts: [client_id: nil, handler: {Tortoise.Handler.Logger, []}], server: %Tortoise.Transport{host: "a2vetinqu6twg7.iot.us-west-2.amazonaws.com", opts: [:binary, {:packet, :raw}, {:active, false}, {:verify, :verify_peer}, {:certfile, './config/client-certificate.pem.key'}, {:keyfile, './config/client-private.pem.key'}, {:cacertfile, "config/VeriSign-Class-3-Public-Primary-Certification-Authority-G5.pem.crt"}, {:protocol_version, :"tlsv1.2"}], port: 8883, type: Tortoise.Transport.SSL}, subscriptions: %Tortoise.Package.Subscribe{__META__: %Tortoise.Package.Meta{flags: 2, opcode: 8}, identifier: nil, topics: [{"#", 0}]}}
[error] GenServer {Tortoise.Registry, {Tortoise.Connection, nil}} terminating
** (WithClauseError) no with clause matching: {:error, {:options, {:socket_options, [protocol_version: :"tlsv1.2", packet_size: 0, packet: 0, header: 0, active: false, mode: :binary]}}}
    (tortoise) lib/tortoise/connection.ex:423: Tortoise.Connection.do_connect/2
    (tortoise) lib/tortoise/connection.ex:261: Tortoise.Connection.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :connect

...

    ** (EXIT) time out
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    lib/reverie/cli.ex:54: anonymous fn/1 in Reverie.Cli.handle_chunk/1
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    lib/reverie/cli.ex:53: Reverie.Cli.handle_chunk/1
    (elixir) lib/stream.ex:419: anonymous fn/4 in Stream.each/2
    (elixir) lib/stream.ex:1524: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:263: Stream.after_chunk_while/2

```

Tag: @connorjacobsen

**Comment by voltone** [comment]
The line `protocol_version: :"tlsv1.2"` should read `versions: [:"tlsv1.2"]`

**Comment by gausby** [comment]
The returned error seem to originate from the `:ssl` module, so I think it is a misconfiguration. I think the culprit is the `protocol_version` option, because I cannot see it in the options specification in the :ssl documentation. I will look into the SSL module a bit more if I have any time when I get home from my day job.

**Comment by gausby** [comment]
@powersjcb did you make it work ?

**Comment by powersjcb** [comment]
@gausby It turns out the original failure mode was me using the wrong input type for the hostname.

`"[***].iot.us-west-2.amazonaws.com" -> '[***].iot.us-west-2.amazonaws.com'`

I'm still running into a problems, though now it's handshake related. :-\

```    
    Tortoise.Supervisor.start_child(
      client_id: "123456",
      version: config.version,
      handler: {Tortoise.Handler.Logger, []},
      server: {
        Tortoise.Transport.SSL,
        host: 'a2vetinqu6twg7.iot.us-west-2.amazonaws.com',
        port: 8883,
        certfile: "/Users/jacobpowers/workspace/knox/apps/knox/priv/client-certificate.crt.pem",
        keyfile: "/Users/jacobpowers/workspace/knox/apps/knox/priv/client-private.key.pem",
        cacerts: :certifi.cacerts(),
        versions: [:"tlsv1.2"],
      },
      subscriptions: [{"#", 0}]
    )
```

Stacktrace:
```
...
[info] ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'certify', 32, 'at ssl_handshake.erl:1335 generated CLIENT ALERT: Fatal - Handshake Failure - {bad_cert,hostname_check_failed}', 10]
[error] GenServer {Tortoise.Registry, {Tortoise.Connection, "123456"}} terminating
** (WithClauseError) no with clause matching: {:error, {:tls_alert, 'handshake failure'}}
    (tortoise) lib/tortoise/connection.ex:423: Tortoise.Connection.do_connect/2
    (tortoise) lib/tortoise/connection.ex:261: Tortoise.Connection.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :connect
State: %Tortoise.Connection{backoff: %Tortoise.Connection.Backoff{max_interval: 30000, min_interval: 100, value: nil}, connect: %Tortoise.Package.Connect{__META__: %Tortoise.Package.Meta{flags: 0, opcode: 1}, clean_session: true, client_id: "123456", keep_alive: 60, password: nil, protocol: "MQTT", protocol_version: 4, user_name: nil, will: nil}, keep_alive: nil, opts: [client_id: "123456", handler: {Tortoise.Handler.Logger, []}], server: %Tortoise.Transport{host: 'a2vetinqu6twg7.iot.us-west-2.amazonaws.com', opts: [:binary, {:packet, :raw}, {:active, false}, {:verify, :verify_peer}, {:certfile, "/Users/jacobpowers/workspace/knox/apps/knox/priv/client-certificate.crt.pem"}, {:keyfile, "/Users/jacobpowers/workspace/knox/apps/knox/priv/client-private.key.pem"}, {:cacerts, [<<48, 130, 4, 99, 48, 130, 3, 75, 160, 3, 2, 1, 2, 2, 1, 1, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 129, ...>>, <<48, 130, 5, 195, 48, 130, 3, 171, 160, 3, 2, 1, 2, 2, 20, 10, 126, 166, 223, 75, 68, 158, 218, 106, 36, 133, 158, 230, 184, 21, 211, 22, ...>>, <<48, 130, 1, 242, 48, 130, 1, 120, 160, 3, 2, 1, 2, 2, 19, 6, 108, 159, 215, 193, 187, 16, 76, 41, 67, 229, 113, 123, 123, 44, 200, ...>>, <<48, 130, 1, 182, 48, 130, 1, 91, 160, 3, 2, 1, 2, 2, 19, 6, 108, 159, 213, 116, 151, 54, 102, 63, 59, 11, 154, 217, 232, 158, ...>>, <<48, 130, 5, 65, 48, 130, 3, 41, 160, 3, 2, 1, 2, 2, 19, 6, 108, 159, 210, 150, 53, 134, 159, 10, 15, 229, 134, 120, 248, ...>>, <<48, 130, 3, 65, 48, 130, 2, 41, 160, 3, 2, 1, 2, 2, 19, 6, 108, 159, 207, 153, 191, 140, 10, 57, 226, 240, 120, 138, ...>>, <<48, 130, 5, 131, 48, 130, 3, 107, 160, 3, 2, 1, 2, 2, 15, 93, 147, 141, 48, 103, 54, 200, 6, 29, 26, 199, 84, ...>>, <<48, 130, 5, 107, 48, 130, 3, 83, 160, 3, 2, 1, 2, 2, 17, 0, 130, 16, 207, 176, 210, 64, 227, 89, 68, 99, ...>>, <<48, 130, 2, 33, 48, 130, 1, 166, 160, 3, 2, 1, 2, 2, 18, 17, 32, 230, 248, 76, 252, 36, 176, 190, 5, ...>>, <<48, 130, 5, 111, 48, 130, 3, 87, 160, 3, 2, 1, 2, 2, 18, 17, 32, 161, 105, 27, 191, 189, 185, 189, ...>>, <<48, 130, 5, 111, 48, 130, 3, 87, 160, 3, 2, 1, 2, 2, 18, 17, 32, 179, 144, 85, 57, 125, 127, ...>>, <<48, 130, 2, 28, 48, 130, 1, 162, 160, 3, 2, 1, 2, 2, 18, 17, 32, 217, 145, 206, 174, 163, ...>>, <<48, 130, 5, 107, 48, 130, 3, 83, 160, 3, 2, 1, 2, 2, 18, 17, 32, 85, 131, 228, 45, ...>>, <<48, 130, 2, 195, 48, 130, 2, 74, 160, 3, 2, 1, 2, 2, 1, 0, 48, 10, 6, 8, ...>>, <<48, 130, 6, 11, 48, 130, 3, 243, 160, 3, 2, 1, 2, 2, 1, 0, 48, 13, 6, ...>>, <<48, 130, 5, 210, 48, 130, 3, 186, 160, 3, 2, 1, 2, 2, 16, 33, 214, 208, ...>>, <<48, 130, 3, 114, 48, 130, 2, 90, 160, 3, 2, 1, 2, 2, 20, 62, 138, ...>>, <<48, 130, 2, 9, 48, 130, 1, 143, 160, 3, 2, 1, 2, 2, 16, 104, ...>>, <<48, 130, 3, 124, 48, 130, 2, 100, 160, 3, 2, 1, 2, 2, 16, ...>>, <<48, 130, 3, 181, 48, 130, 2, 157, 160, 3, 2, 1, 2, 2, ...>>, <<48, 130, 5, 146, 48, 130, 3, 122, 160, 3, 2, 1, 2, ...>>, <<48, 130, 4, 39, 48, 130, 3, 15, 160, 3, 2, 1, ...>>, <<48, 130, 5, 141, 48, 130, 3, 117, 160, 3, 2, ...>>, <<48, 130, 2, 249, 48, 130, 2, 128, 160, 3, ...>>, <<48, 130, 4, 62, 48, 130, 3, 38, 160, ...>>, <<48, 130, 5, 102, 48, 130, 3, 78, ...>>, <<48, 130, 5, 96, 48, 130, 3, ...>>, <<48, 130, 5, 112, 48, 130, ...>>, <<48, 130, 5, 116, 48, ...>>, <<48, 130, 2, 30, ...>>, <<48, 130, 1, ...>>, <<48, 130, ...>>, <<48, ...>>, <<...>>, ...]}, {:versions, [:"tlsv1.2"]}], port: 8883, type: Tortoise.Transport.SSL}, subscriptions: %Tortoise.Package.Subscribe{__META__: %Tortoise.Package.Meta{flags: 2, opcode: 8}, identifier: nil, topics: [{"#", 0}]}}
...
```

Here's a gist of a verification I created to prove to myself that my certificates are setup correctly with AWS. https://gist.github.com/powersjcb/d48651da054c34d0c1d615011af2906c

**Comment by powersjcb** [comment]
Though, it looks like everything works if I use `verify: :verify_none`. :joy:

**Comment by gausby** [comment]
Perhaps you need to turn the values passed as `certfile` and `keyfile` into charlists as well; In Elixir strings with `"`'s are binaries, and single pings `'` are charlists—historical Erlang reasons :).

```elixir
    Tortoise.Supervisor.start_child(
      client_id: "123456",
      version: config.version,
      handler: {Tortoise.Handler.Logger, []},
      server: {
        Tortoise.Transport.SSL,
        host: 'a2vetinqu6twg7.iot.us-west-2.amazonaws.com',
        port: 8883,
        certfile: '/Users/jacobpowers/workspace/knox/apps/knox/priv/client-certificate.crt.pem',
        keyfile: '/Users/jacobpowers/workspace/knox/apps/knox/priv/client-private.key.pem',
        cacerts: :certifi.cacerts(),
        versions: [:"tlsv1.2"],
      },
      subscriptions: [{"#", 0}]
    )
```

Does that improve the situation?

**Comment by gausby** [comment]
This is because `:ssl` is an Erlang module, and it has slightly different expectations of the input; tons of places are using charlists instead of binaries. I am considering coercing the input given to the SSL transport so it will convert binaries to charlists. That would improve overall usability of Tortoise :)

**Comment by powersjcb** [comment]
Huzzah! I got it working. I think there's a problem with the AWS IoT wildcard certs and the default way erlang handles them.

I just got it working by adding `server_name_indication: '*.iot.us-west-2.amazonaws.com'`.

```
Tortoise.Supervisor.start_child(
      client_id: @server_client_id,
      version: config.version,
      handler: {Tortoise.Handler.Logger, []},
      server: {
        Tortoise.Transport.SSL,
        host: 'a2vetinqu6twg7.iot.us-west-2.amazonaws.com',
        port: 8883,
        certfile: "apps/knox/priv/client-certificate.crt.pem",
        keyfile: "apps/knox/priv/client-private.key.pem",
        cacerts: :certifi.cacerts(),
        versions: [:'tlsv1.2'],
        server_name_indication: '*.iot.us-west-2.amazonaws.com',
      },
      subscriptions: [{"#", 0}]
    )
```

**Comment by powersjcb** [comment]
Here's a reference to another instance of this problem.
https://github.com/PagerDuty/analytics-elixir/pull/1/files

**Comment by gausby** [comment]
That is great news! Thanks for figuring this out. I will think about how to improve the usability of creating connections, and I will try to improve the documentation with the lessons learned.

Don’t be shy if you have suggestions on how to improve the project :)

**Comment by voltone** [comment]
This is a known issue with Erlang's `:ssl`, documented [here](
https://bugs.erlang.org/browse/ERL-542).

The bottom line is that the OTP team believe the handling of wildcard certificates depends on the higher-layer protocol. The TLS implementation should be generic, and the user of the `:ssl` APIs (e.g. an HTTP or MQTT client) should tune the server name verification as needed. The [pkix_verify_hostname_match_fun/1](
http://erlang.org/doc/man/public_key.html#pkix_verify_hostname_match_fun-1) function and `customize_hostname_check` SSL option were added for this in OTP 21.

The workaround of sending the wildcard as SNI could result in interop issues with the server. The new OTP 21 options obviously only work with OTP 21. An alternative would be to replace OTP's server certificate verification with the [ssl_verify_fun](https://hex.pm/packages/ssl_verify_fun) package. This is what Hackney/HTTPoison use.

**Comment by voltone** [comment]
If you're on OTP 21 you could try the following:

```elixir
Tortoise.Supervisor.start_child(
      client_id: @server_client_id,
      version: config.version,
      handler: {Tortoise.Handler.Logger, []},
      server: {
        Tortoise.Transport.SSL,
        host: 'a2vetinqu6twg7.iot.us-west-2.amazonaws.com',
        port: 8883,
        certfile: "apps/knox/priv/client-certificate.crt.pem",
        keyfile: "apps/knox/priv/client-private.key.pem",
        cacerts: :certifi.cacerts(),
        versions: [:'tlsv1.2'],
        customize_hostname_check: [match_fun: :public_key.pkix_verify_hostname_match_fun(:https)]
      },
      subscriptions: [{"#", 0}]
    )
```

This uses the [RFC6125](https://tools.ietf.org/html/rfc6125) rules for HTTPS, which I think apply to MQTT as well.

**Comment by gausby** [comment]
Ping @powersjcb; can I close this issue ?

**Comment by powersjcb** [comment]
Yeah, I think we can mark this as resolved. 

It might be helpful to mention this issue in the readme for anyone that wants to setup with AWS, but its non-blocking. (We ended up going with @voltone's proposed solution.)
